[build]
  command = "go build -o functions/main scripts/main.go"
  functions = "functions"
  publish = "scripts"

[build.environment]
  GO_IMPORT_PATH = "github.com/dediirawanuti/golang-mysql"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main"
  status = 200
